import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  floatingBackButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 40 : 40,
    left: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    zIndex: 10,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
    paddingTop: Platform.OS === 'ios' ? 30 : 20,
  },
  formContainer: {
    paddingHorizontal:24,
    paddingVertical: 10,
    backgroundColor: 'transparent',
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: 32,
    marginTop: 16,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: 20,
    marginTop: 12,
    letterSpacing: 0.3,
  },
  inputContainer: {
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  textInput: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontSize: 16,
    color: '#1e293b',
    borderWidth: 2,
    borderColor: '#e2e8f0',
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  textInputFocused: {
    borderColor: '#FF9BB5',
    backgroundColor: '#ffffff',
    shadowOpacity: 0.1,
  },
  pickerContainer: {
    marginBottom: 20,
  },
  pickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  pickerText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1e293b',
    marginLeft: 12,
    flex: 1,
    letterSpacing: 0.2,
  },
  expandedSection: {
    marginBottom: 24,
  },
  calendarContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
    paddingHorizontal: 8,
  },
  calendarNavButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 155, 181, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 155, 181, 0.2)',
  },
  calendarTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1e293b',
    letterSpacing: 0.3,
  },
  weekHeader: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
    paddingHorizontal: 8,
  },
  weekDay: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
    width: 36,
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  daysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  emptyDay: {
    width: 40,
    height: 40,
    margin: 2,
  },
  dayButton: {
    width: 40,
    height: 40,
    margin: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  selectedDay: {
    backgroundColor: '#FF9BB5',
    shadowColor: '#FF9BB5',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  dayText: {
    fontSize: 16,
    color: '#475569',
    fontWeight: '500',
  },
  selectedDayText: {
    color: 'white',
    fontWeight: '700',
  },
  timeSection: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  timePickerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    gap: 30,
  },
  timePicker: {
    alignItems: 'center',
  },
  timeLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 16,
    letterSpacing: 0.2,
  },
  timeDialContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 155, 181, 0.1)',
    borderWidth: 2,
    borderColor: '#FF9BB5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  timeDialSelected: {
    borderColor: '#FF6B9D',
    backgroundColor: 'rgba(255, 107, 157, 0.15)',
  },
  timeText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FF6B9D',
    letterSpacing: 0.5,
  },
  timeSelectedText: {
    color: '#FF6B9D',
  },
  participantSection: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  participantRow: {
    flexDirection: 'row',
    gap: 20,
    marginTop: 8,
  },
  participantInput: {
    flex: 1,
    alignItems: 'center',
  },
  participantLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 16,
    letterSpacing: 0.2,
  },
  participantPickerContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 155, 181, 0.1)',
    borderWidth: 2,
    borderColor: '#FF9BB5',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  participantPickerSelected: {
    borderColor: '#FF6B9D',
    backgroundColor: 'rgba(255, 107, 157, 0.15)',
  },
  participantCount: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FF6B9D',
  },
  participantCountSelected: {
    color: '#FF6B9D',
  },
  participantButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  participantButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e2e8f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  participantButtonActive: {
    backgroundColor: '#FF6B9D',
  },
  descriptionContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#64748b',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  descriptionInput: {
    height: 260,
    textAlignVertical: 'top',
    paddingTop: 14,
    lineHeight: 24,
    fontSize: 16,
    borderWidth: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 4,
  },
  bottomSpacing: {
    height: 24,
  },
  floatingButtonContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 24,
    paddingVertical: 24,
    paddingBottom: 40,
  },
  createButton: {
    borderRadius: 28,
    shadowColor: '#FF6B9D',
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 15,
    elevation: 8,
  },
  createButtonInner: {
    paddingVertical: 18,
    alignItems: 'center',
    borderRadius: 28,
  },
  disabledButton: {
    opacity: 0.6,
    shadowOpacity: 0.15,
  },
  createButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
}); 