/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/css/auth.styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CalendarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EventDetailScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EventListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EventListScreenCopy`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/AuthNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/FindIdScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/OnboardingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/SignupCompleteScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/services/auth`; params?: Router.UnknownInputParams; } | { pathname: `/view/EventCard`; params?: Router.UnknownInputParams; } | { pathname: `/view/detail`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/find-id`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/css/auth.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/CalendarScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/EventDetailScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/EventListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/EventListScreenCopy`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/AuthNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/FindIdScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/OnboardingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/SignupCompleteScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/SignupScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/auth/SplashScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/services/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/view/EventCard`; params?: Router.UnknownOutputParams; } | { pathname: `/view/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/find-id`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/css/auth.styles${`?${string}` | `#${string}` | ''}` | `/screens/CalendarScreen${`?${string}` | `#${string}` | ''}` | `/screens/EventDetailScreen${`?${string}` | `#${string}` | ''}` | `/screens/EventListScreen${`?${string}` | `#${string}` | ''}` | `/screens/EventListScreenCopy${`?${string}` | `#${string}` | ''}` | `/screens/auth/AuthNavigator${`?${string}` | `#${string}` | ''}` | `/screens/auth/FindIdScreen${`?${string}` | `#${string}` | ''}` | `/screens/auth/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/auth/OnboardingScreen${`?${string}` | `#${string}` | ''}` | `/screens/auth/SignupCompleteScreen${`?${string}` | `#${string}` | ''}` | `/screens/auth/SignupScreen${`?${string}` | `#${string}` | ''}` | `/screens/auth/SplashScreen${`?${string}` | `#${string}` | ''}` | `/services/auth${`?${string}` | `#${string}` | ''}` | `/view/EventCard${`?${string}` | `#${string}` | ''}` | `/view/detail${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/auth/find-id${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/css/auth.styles`; params?: Router.UnknownInputParams; } | { pathname: `/screens/CalendarScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EventDetailScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EventListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EventListScreenCopy`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/AuthNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/FindIdScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/OnboardingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/SignupCompleteScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/auth/SplashScreen`; params?: Router.UnknownInputParams; } | { pathname: `/services/auth`; params?: Router.UnknownInputParams; } | { pathname: `/view/EventCard`; params?: Router.UnknownInputParams; } | { pathname: `/view/detail`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/find-id`; params?: Router.UnknownInputParams; };
    }
  }
}
